name: cppcheck-action
on: [push, pull_request]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cppcheck
        uses: chmorgan/cppcheck-action@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline_suppression: enable
          other_options: --suppress=missingInclude
