name: cppcheck-action
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install --yes cppcheck

      - name: cppcheck
        run: ./scripts/run-cppcheck.sh
